### ISSUE TITLE
Write regression tests that mock IO.

### ISSUE THREAD

**Issue by haesbaert** [haesbaert/charrua-core#14]
It's horrible having to have a dhcp setup to actually test things, we should have regression tests that mock io and simulates a server/client in different cases.

**Comment by hannesm** [comment]
you've seen https://github.com/yomimono/mirage-net-pcap which might help there? (there's also another idea, if you have a purely functional core, you can just plug your test onto that interface, instead of at the I/O layer... sth like `handle : state -> buffer -> (state * action)`)...

**Comment by haesbaert** [comment]
I was thinking on something more like the second case you described, the core is almost purely functional, the lease database is not, but that can be sorted out.

Since I added support to run on unix (outside of mirage), there is a module abstraction for an "interface", which encompasses how to receive/send packets, my idea was to use that abstraction to do the fake io between the client and the server.

**Comment by hannesm** [comment]
sounds good to me! :D

**Comment by haesbaert** [comment]
Awesomo :D!

**Comment by haesbaert** [comment]
this is happening.

**Comment by haesbaert** [comment]
Done, still needs more tests though.
