### ISSUE TITLE
Support dhcp option 121.

### ISSUE THREAD

**Issue by haesbaert** [haesbaert/charrua-core#15]
What ever that is.

**Comment by hannesm** [comment]
you clearly know about the authoritative registry at https://www.iana.org/assignments/bootp-dhcp-parameters/bootp-dhcp-parameters.xhtml :)

**Comment by haesbaert** [comment]
Bah I didnt know, I was chasing all the rfcs, that should make things
easier, thanks !

**Comment by haesbaert** [comment]
I've added the option code at least.

**Comment by haesbaert** [comment]
Supported as a raw string now.
