### ISSUE TITLE
readme refers to charrua-mirage repository, which has gone missing

### ISSUE THREAD

**Issue by yomimono** [haesbaert/charrua-core#23]
The README has a link to http://github.com/haesbaert/charrua-mirage, but it looks like only charrua-core and charrua-unix are present.  Is the Mirage example still kicking around somewhere?

**Comment by haesbaert** [comment]
Thanks I fixed it this afternoon, didn't push it yet since I'm preparing the release.

The example is in mirage-skeleton, I've corrected the README to point there, will push in a few secs.

**Comment by haesbaert** [comment]
Fixed, it points now to: https://github.com/mirage/mirage-skeleton/tree/master/dhcp
