### ISSUE TITLE
cut a release?

### ISSUE THREAD

**Issue by yomimono** [haesbaert/charrua-core#25]
Any plan for cutting an 0.3 release soon?

**Comment by haesbaert** [comment]
Yep, i have it all set, got some delays, had to fix ppx in cstruct which
David did most of the job, I frankly slacked the hole easter, will try to
do tonigth.

**Comment by yomimono** [comment]
Awesome!  I asked because in trying to get some tests to pass which test against charrua-core as a reverse dependency (see https://github.com/ocaml/opam-repository/pull/6100 ), there didn't seem to be a combination of charrua-core and mirage-skeleton's dhcp example that's currently buildable out of the box.

I have a patch to mirage-skeleton's `dhcp` unikernel that gets it working with the current master -- I'll PR it once charrua-core 0.3 is out.  (It's at https://github.com/yomimono/mirage-skeleton/blob/charrua-0.3/dhcp/unikernel.ml if for some reason you want a sneak peek.)
