### ISSUE TITLE
Allow empty range in server configuration.

### ISSUE THREAD

**Issue by yomimono** [haesbaert/charrua-core#27]
It's useful to be able to create a DHCP server that serves addresses only in response to "registered" MAC addresses -- in other words, to have no general address range, but serve only fixed addresses that match known hosts.  `Dhcp_server.Config.t` doesn't currently allow this, as `range` is not an `option` field.

**Comment by haesbaert** [comment]
I think this is useful but will require some work, I'll write it.

**Comment by haesbaert** [comment]
Implemented in 0bb4464f41dab7fadc37bdda606fe76edaefc6d3 , can't test at this time but I'm writing regression tests for it.

**Comment by yomimono** [comment]
Thanks a lot for that implementation, @haesbaert ! :)

**Comment by haesbaert** [comment]
happy to help 👯
