### ISSUE TITLE
Should hosts inherit network settings from the general pool?

### ISSUE THREAD

**Issue by yomimono** [haesbaert/charrua-core#28]
I'm configuring a server by assembling a `Dhcp_server.Config.t` . I have one `host` included in the list.  I was surprised that when there's no `Subnet_mask` set in the `host`'s list of `options`, it doesn't inherit one from the more general network configuration in the `Dhcp_server.Config.t`.  Is this a bug, or just a failure of understanding on my part?

**Comment by haesbaert** [comment]
It should advertise the Subnet_mask on a DHCPOFFER, but the option itself will not show up in the hosts lists, if this is not happening, it is a bug, I did some changes and might have introduced it recently.

**Comment by haesbaert** [comment]
Hmm it seems I'm ignoring hosts.options, but the subnet mask should be included anyway.
But if you add a host specific option that is not address or lease time, it will get ignored, I'll fix it.

**Comment by haesbaert** [comment]
Fixed in 957314856975727cd19d5da6003ccf11faa736d6
